import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().optional(),
  DB_HOST: Joi.string().default('localhost'),
  DB_PORT: Joi.number().default(5432),
  DB_USER: Joi.string().default('photo'),
  DB_PASS: Joi.string().default('photo'),
  DB_NAME: Joi.string().default('photo'),
  REDIS_URL: Joi.string().default('redis://localhost:6379'),
  S3_ENDPOINT: Joi.string().required(),
  S3_REGION: Joi.string().default('us-east-1'),
  S3_ACCESS_KEY: Joi.string().required(),
  S3_SECRET_KEY: Joi.string().required(),
  S3_BUCKET: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
  GOOGLE_CLIENT_ID: Joi.string().optional(),
  GOOGLE_CLIENT_SECRET: Joi.string().optional(),
  GOOGLE_CALLBACK_URL: Joi.string().optional(),
  FB_CLIENT_ID: Joi.string().optional(),
  FB_CLIENT_SECRET: Joi.string().optional(),
  FB_CALLBACK_URL: Joi.string().optional(),
  SESSION_SECRET: Joi.string().required(),
  MAIL_PROVIDER: Joi.string().optional(),
  MAIL_API_KEY: Joi.string().optional(),
  SMS_PROVIDER: Joi.string().optional(),
  SMS_API_KEY: Joi.string().optional(),
  NOTIFICATION_BASE_URL: Joi.string().optional(),
  RAZORPAY_KEY_ID: Joi.string().required(),
  RAZORPAY_KEY_SECRET: Joi.string().required(),
  METRICS_ENABLED: Joi.string().optional(),
});
